// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/activity" | "/admin/analytics" | "/admin/calls" | "/admin/chats" | "/admin/claims" | "/admin/employees" | "/admin/jobs" | "/admin/notifications" | "/admin/reports" | "/admin/settings" | "/admin/support-chats" | "/admin/transactions" | "/admin/users" | "/admin/users/[uid]" | "/admin/verifications" | "/dashboard" | "/dashboard/analytics" | "/dashboard/calendar" | "/dashboard/clients" | "/dashboard/find" | "/dashboard/jobs" | "/dashboard/jobs/[jobId]" | "/dashboard/jobs/new" | "/dashboard/log" | "/dashboard/messages" | "/dashboard/messages/[chatId]" | "/dashboard/profile" | "/dashboard/settings" | "/dashboard/transactions" | "/dashboard/u/[uid]" | "/junk" | "/login" | "/mobile-redesign-temp" | "/mobile-upload" | "/onboarding" | "/photo-upload" | "/signup"
type AppRouteHandlerRoutes = "/api/admin/jobs/[jobId]" | "/api/admin/users/[uid]" | "/api/email/welcome" | "/api/jobs/action" | "/api/jobs/cancel" | "/api/jobs/cash-payment" | "/api/jobs/confirm-cash" | "/api/jobs/create" | "/api/jobs/photo-transfer" | "/api/mobile-upload/session/consume" | "/api/mobile-upload/session/create" | "/api/mobile-upload/session/upload" | "/api/network-origin" | "/api/notifications/message" | "/api/operators/nearby-clients" | "/api/stripe/account-link" | "/api/stripe/account-session" | "/api/stripe/account-status" | "/api/stripe/cancel-payment" | "/api/stripe/capture-payment" | "/api/stripe/create-connect-account" | "/api/stripe/create-payment-intent" | "/api/stripe/payment-status" | "/api/stripe/webhook" | "/api/support-calls"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/dashboard" | "/junk"
type RedirectRoutes = never
type RewriteRoutes = "/__/auth/[[...path]]" | "/__/firebase/init.json"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/__/auth/[[...path]]": { "path"?: string[]; }
  "/__/firebase/init.json": {}
  "/admin": {}
  "/admin/activity": {}
  "/admin/analytics": {}
  "/admin/calls": {}
  "/admin/chats": {}
  "/admin/claims": {}
  "/admin/employees": {}
  "/admin/jobs": {}
  "/admin/notifications": {}
  "/admin/reports": {}
  "/admin/settings": {}
  "/admin/support-chats": {}
  "/admin/transactions": {}
  "/admin/users": {}
  "/admin/users/[uid]": { "uid": string; }
  "/admin/verifications": {}
  "/api/admin/jobs/[jobId]": { "jobId": string; }
  "/api/admin/users/[uid]": { "uid": string; }
  "/api/email/welcome": {}
  "/api/jobs/action": {}
  "/api/jobs/cancel": {}
  "/api/jobs/cash-payment": {}
  "/api/jobs/confirm-cash": {}
  "/api/jobs/create": {}
  "/api/jobs/photo-transfer": {}
  "/api/mobile-upload/session/consume": {}
  "/api/mobile-upload/session/create": {}
  "/api/mobile-upload/session/upload": {}
  "/api/network-origin": {}
  "/api/notifications/message": {}
  "/api/operators/nearby-clients": {}
  "/api/stripe/account-link": {}
  "/api/stripe/account-session": {}
  "/api/stripe/account-status": {}
  "/api/stripe/cancel-payment": {}
  "/api/stripe/capture-payment": {}
  "/api/stripe/create-connect-account": {}
  "/api/stripe/create-payment-intent": {}
  "/api/stripe/payment-status": {}
  "/api/stripe/webhook": {}
  "/api/support-calls": {}
  "/dashboard": {}
  "/dashboard/analytics": {}
  "/dashboard/calendar": {}
  "/dashboard/clients": {}
  "/dashboard/find": {}
  "/dashboard/jobs": {}
  "/dashboard/jobs/[jobId]": { "jobId": string; }
  "/dashboard/jobs/new": {}
  "/dashboard/log": {}
  "/dashboard/messages": {}
  "/dashboard/messages/[chatId]": { "chatId": string; }
  "/dashboard/profile": {}
  "/dashboard/settings": {}
  "/dashboard/transactions": {}
  "/dashboard/u/[uid]": { "uid": string; }
  "/junk": {}
  "/login": {}
  "/mobile-redesign-temp": {}
  "/mobile-upload": {}
  "/onboarding": {}
  "/photo-upload": {}
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/dashboard": never
  "/junk": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
