// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/admin/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/activity">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/calls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/calls">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/calls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/chats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/chats">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/chats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/claims/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/claims">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/claims/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/employees">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/jobs">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/support-chats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support-chats">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/support-chats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/transactions">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/users/[uid]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users/[uid]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/users/[uid]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/verifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/verifications">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/verifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/calendar">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/clients">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/find/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/find">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/find/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/jobs/[jobId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/jobs/[jobId]">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/jobs/[jobId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/jobs/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/jobs/new">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/jobs/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/jobs">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/log">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/messages/[chatId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/messages/[chatId]">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/messages/[chatId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/messages">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/transactions">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/u/[uid]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/u/[uid]">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/u/[uid]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/junk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/junk">> = Specific
  const handler = {} as typeof import("../../../src/app/junk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/mobile-redesign-temp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mobile-redesign-temp">> = Specific
  const handler = {} as typeof import("../../../src/app/mobile-redesign-temp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/mobile-upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mobile-upload">> = Specific
  const handler = {} as typeof import("../../../src/app/mobile-upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/photo-upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/photo-upload">> = Specific
  const handler = {} as typeof import("../../../src/app/photo-upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/jobs/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/jobs/[jobId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/jobs/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/users/[uid]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[uid]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/users/[uid]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/email/welcome/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/welcome">> = Specific
  const handler = {} as typeof import("../../../src/app/api/email/welcome/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/jobs/action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/action">> = Specific
  const handler = {} as typeof import("../../../src/app/api/jobs/action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/jobs/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/api/jobs/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/jobs/cash-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/cash-payment">> = Specific
  const handler = {} as typeof import("../../../src/app/api/jobs/cash-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/jobs/confirm-cash/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/confirm-cash">> = Specific
  const handler = {} as typeof import("../../../src/app/api/jobs/confirm-cash/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/jobs/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/create">> = Specific
  const handler = {} as typeof import("../../../src/app/api/jobs/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/jobs/photo-transfer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/photo-transfer">> = Specific
  const handler = {} as typeof import("../../../src/app/api/jobs/photo-transfer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/mobile-upload/session/consume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile-upload/session/consume">> = Specific
  const handler = {} as typeof import("../../../src/app/api/mobile-upload/session/consume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/mobile-upload/session/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile-upload/session/create">> = Specific
  const handler = {} as typeof import("../../../src/app/api/mobile-upload/session/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/mobile-upload/session/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile-upload/session/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/mobile-upload/session/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/network-origin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/network-origin">> = Specific
  const handler = {} as typeof import("../../../src/app/api/network-origin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notifications/message/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/message">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notifications/message/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/operators/nearby-clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operators/nearby-clients">> = Specific
  const handler = {} as typeof import("../../../src/app/api/operators/nearby-clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stripe/account-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/account-link">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stripe/account-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stripe/account-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/account-session">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stripe/account-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stripe/account-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/account-status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stripe/account-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stripe/cancel-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/cancel-payment">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stripe/cancel-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stripe/capture-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/capture-payment">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stripe/capture-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stripe/create-connect-account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/create-connect-account">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stripe/create-connect-account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stripe/create-payment-intent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/create-payment-intent">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stripe/create-payment-intent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stripe/payment-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/payment-status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stripe/payment-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/support-calls/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/support-calls">> = Specific
  const handler = {} as typeof import("../../../src/app/api/support-calls/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/junk/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/junk">> = Specific
  const handler = {} as typeof import("../../../src/app/junk/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
